import "./globals.css";
import Script from "next/script";
import { UserProvider } from "@/components/UserComponnet";
import { BalanceProvider } from "@/components/BalanceStore";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* اسکریپت رو میاری داخل Body */}
        <Script
          src="https://telegram.org/js/telegram-web-app.js"
        />
      </head>

      <body
        className="
          font-inter
          antialiased"
      >
        <UserProvider>
          <BalanceProvider>
            {children}
          </BalanceProvider>
        </UserProvider>
      </body>
    </html>
  );
}
